version: '3.8'

services:
  react-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3000" # Changed to match vite config port 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
